### ISSUE TITLE
Check website security

### ISSUE THREAD

**Issue by LoryPelli** [discordcf/discordcf.org#3]
![Screenshot_2022-12-23-07-22-31-326-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/87276663/209283158-4d6bceaf-6d35-48e7-a723-3ac52c48ecfd.jpg)
It says this

**Comment by LoryPelli** [comment]
It seems only on mobile...

**Comment by alvgaona** [comment]
It's actually a Cloudflare problem with their certificates. Once we get an official domain, it should be solved.

**Comment by alvgaona** [comment]
I'll create another issue with more context.
